# This file was generated by GoReleaser. DO NOT EDIT.
cask "xmtpd-cli" do
  name "xmtpd-cli"
  desc "CLI to manage the XMTP Network."
  homepage "https://github.com/xmtp/xmtpd"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xmtpd-cli"
  bash_completion "completions/xmtpd-cli.bash"
  zsh_completion "completions/_xmtpd-cli"
  fish_completion "completions/xmtpd-cli.fish"

  on_macos do
    on_intel do
      url "https://github.com/xmtp/xmtpd/releases/download/v#{version}/xmtpd-cli_#{version}_darwin_amd64.zip"
      sha256 "85a17db42216a4289fdbc2e91df389922179d8be3c13d9cffadef14a8ab75926"
    end
    on_arm do
      url "https://github.com/xmtp/xmtpd/releases/download/v#{version}/xmtpd-cli_#{version}_darwin_arm64.zip"
      sha256 "c153327d3bb80fc3582514b12196548650f299a54f3138896e25604c5cf4efcf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/xmtp/xmtpd/releases/download/v#{version}/xmtpd-cli_#{version}_linux_amd64.zip"
      sha256 "9fd6216c813e566dd595f1e03237f7dedb7765e022b62c6e3972588f3fb73856"
    end
    on_arm do
      url "https://github.com/xmtp/xmtpd/releases/download/v#{version}/xmtpd-cli_#{version}_linux_arm64.zip"
      sha256 "6f90fe2407bc222226253f318391321787505ced49b5fca3b50aa60af84f8d60"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xmtpd-cli"]
    end
  end

  caveats do
    "xmtpd-cli is not notarized. The installer removes the macOS quarantine attribute."
    "Prefer signed/notarized builds when available."
  end

  # No zap stanza required
end
