# This file was generated by GoReleaser. DO NOT EDIT.
cask "xmtpd-cli" do
  name "xmtpd-cli"
  desc "CLI to manage the XMTP Network."
  homepage "https://github.com/xmtp/xmtpd"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xmtpd-cli"
  bash_completion "completions/xmtpd-cli.bash"
  zsh_completion "completions/_xmtpd-cli"
  fish_completion "completions/xmtpd-cli.fish"

  on_macos do
    on_intel do
      url "https://github.com/xmtp/xmtpd/releases/download/v#{version}/xmtpd-cli_#{version}_darwin_amd64.zip"
      sha256 "2e565651930894b1338c560c76f98569764b271df6f68537c01671c3436148bf"
    end
    on_arm do
      url "https://github.com/xmtp/xmtpd/releases/download/v#{version}/xmtpd-cli_#{version}_darwin_arm64.zip"
      sha256 "b84f7c2fa2e7ad7c6a76fc45f5efc035e8a1d223d1b7af1f7ea003591962937f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/xmtp/xmtpd/releases/download/v#{version}/xmtpd-cli_#{version}_linux_amd64.zip"
      sha256 "af199d5439dfec7b08bb0d2b5e09dcf0cf7db58b6968f893598b096e6a1966ed"
    end
    on_arm do
      url "https://github.com/xmtp/xmtpd/releases/download/v#{version}/xmtpd-cli_#{version}_linux_arm64.zip"
      sha256 "762d03189adbbd17c7497e06b16befb294f0d980830470c0769267fa87e4340e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xmtpd-cli"]
    end
  end

  caveats do
    "xmtpd-cli is not notarized. The installer removes the macOS quarantine attribute."
    "Prefer signed/notarized builds when available."
  end

  # No zap stanza required
end
