# This file was generated by GoReleaser. DO NOT EDIT.
cask "xmtpd-cli" do
  name "xmtpd-cli"
  desc "CLI to manage the XMTP Network."
  homepage "https://github.com/xmtp/xmtpd"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xmtpd-cli"
  bash_completion "completions/xmtpd-cli.bash"
  zsh_completion "completions/_xmtpd-cli"
  fish_completion "completions/xmtpd-cli.fish"

  on_macos do
    on_intel do
      url "https://github.com/xmtp/xmtpd/releases/download/v#{version}/xmtpd-cli_#{version}_darwin_amd64.zip"
      sha256 "4120538c5d89e51ede187d7eaa14efb15dc2d41127203dc120689204791202be"
    end
    on_arm do
      url "https://github.com/xmtp/xmtpd/releases/download/v#{version}/xmtpd-cli_#{version}_darwin_arm64.zip"
      sha256 "8d08afa6fb54e1cde089933275ef4a87cb9a8c3cda3b4071cd9267caad78685e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/xmtp/xmtpd/releases/download/v#{version}/xmtpd-cli_#{version}_linux_amd64.zip"
      sha256 "ad088c81f4af9e88f6a3332b2498df2481049ec3e03f9994592feba0e9238e0f"
    end
    on_arm do
      url "https://github.com/xmtp/xmtpd/releases/download/v#{version}/xmtpd-cli_#{version}_linux_arm64.zip"
      sha256 "a9c9668da41d641ebfea034cd542e8deb3aee504fa33a7bc5c27a7201e4ea36f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xmtpd-cli"]
    end
  end

  caveats do
    "xmtpd-cli is not notarized. The installer removes the macOS quarantine attribute."
    "Prefer signed/notarized builds when available."
  end

  # No zap stanza required
end
